### ISSUE TITLE
How do I recreate this?

### ISSUE THREAD

**Issue by vcidst** [AnandChowdhary/life-data#9]
Hello Anand, 

Thanks a lot for creating this! It reminded me of the iconic [Feltron Annual Reports](https://create.adobe.com/2016/3/16/designing_with_data_nicholas_felton.html) I see you've also made the services repo public but do you happen to have a documentation for how can I recreate this setup? I'd like to follow your suit and do this for myself as well

Thanks
Shailendra

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @vcidst! That's right, I don't have comprehensive documentation about recreating my setup, but everything comes from the [AnandChowdhary/service](https://github.com/AnandChowdhary/services) repo, like you rightly pointed out.

You can also see this data visualized on https://anandchowdhary.com/life/.

Here's what I can do: I'll write a nice long blog post about exactly how this setup works, like a tutorial you'll be able to follow. But I'm not sure how quickly I can churn that out, so I'll leave this issue open.

**Comment by AnandChowdhary** [comment]
This is now public! Visit https://github.com/AnandChowdhary/life, the new life data repository, with a simple guide to recreating it.
